site_name: CryptoFuzz
site_author: 'Pymmdrza@gmail.com'
repo_url: 'https://github.com/Pymmdrza/cryptoFuzz'
edit_uri: '?query=root/path/docs/'
site_description: 'cryptoFuzz a fast and easy Python package for generating private keys and mnemonics, converting seeds, binary, and decimals.'
site_url: 'https://pymmdrza.gitbook.io/cryptoFuzz'
copyright: 'Copyright © 2023, Pymmdrza'

nav:
    - Home: index.md
    - Use in Windows: '#windows'
    - Use in Linux/Mac: '#linux--mac'
    - Git: '#git'
    - document: 'https://github.com/Pymmdrza/cryptoFuzz'
    - Bug Tracking: 'https://github.com/Pymmdrza/cryptoFuzz/issues'
    - Pull Requests: 'https://github.com/Pymmdrza/cryptoFuzz/pulls'
    - Source: 'https://github.com/Pymmdrza/cryptoFuzz'
    - Example: 'https://github.com/Pymmdrza/cryptoFuzz/tree/main/Example'
    - From Private Key: 'https://github.com/Pymmdrza/cryptoFuzz/blob/main/Example/PrivateKey.py'
    - From Mnemonic: 'https://github.com/Pymmdrza/cryptoFuzz/blob/main/Example/Mnemonic.py'
    - From Decimal: 'https://github.com/Pymmdrza/cryptoFuzz/blob/main/Example/Decimal.py'
    - From Wif: 'https://github.com/Pymmdrza/cryptoFuzz/blob/main/Example/Wif.py'
    - Mmdrza.Com: 'https://mmdrza.com'
validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: warn
    absolute_links: info
    unrecognized_links: info
theme:
  name: readthedocs
  locale: en
  collapse_by_default: false
  include_homepage_in_sidebar: true
  features:
    - navigation.tabs
    - navigation.instant

plugins:
  - search:
      indexing: 'full'

markdown_extensions:
  - smarty
  - toc:
      permalink: true
      separator: "-"
  - sane_lists

exclude_docs:
  install.sh
  install.bat
  *.py

