site_name: CryptoFuzz
site_description: 'Documentation for CryptoFuzz'
site_author: 'Pymmdrza@gmail.com'
repo_url: 'https://github.com/Pymmdrza/cryptofuzz'
nav:
    - Home: '/'
    - document: 'https://github.com/Pymmdrza/cryptoFuzz'
    - Bug Tracking: 'https://github.com/Pymmdrza/cryptoFuzz/issues'
    - Pull Requests: 'https://github.com/Pymmdrza/cryptoFuzz/pulls'
    - Source: 'https://github.com/Pymmdrza/cryptoFuzz'
    - Mmdrza.Com: 'https://mmdrza.com'

theme:
    name: 'material'
    features:
        - navigation.top
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
        - navigation.tracking
        - navigation.expand
        - navigation.path
        - navigation.instant.prefetch
        - navigation.instant
        - toc.follow
        - search.suggest
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

docs_dir: './site'
name: CryptoFuzz

# Name of the author
author: Pymmdrza

# Short bio or description (displayed in the header)
description: crypto fuzzing python Package private key (hex) bytes (seed) , mnemonic , binary , Decimal (number), Root Key (xprv) and XPUB , compressed and uncompressed address with public key 

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/reverie.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: pymmdrza@gmail.com
  facebook: mrpymmdrza
  flickr:
  github: Pymmdrza/cryptoFuzz
  instagram:
  linkedin: 
  pinterest:
  rss: rss
  twitter:
  stackoverflow: 
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
  playconsole:


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: 

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
# google_analytics: UA-********-**
#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag
  - jekyll-paginate

include: ['_pages']

paginate: 6
paginate_path: /page:num/

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
plugins:
  - search

